### ISSUE TITLE
[BUG] Targeting Reticle Located to the right of actual aiming location

### ISSUE THREAD

**Issue by LiamCMoore** [Liam-Harrison/Celeritas#102]
**Describe the bug**
The location the player is aiming should be indicated by the small red reticle where the mouse is. This is not currently accurate and caused your attacks to be extremely frustrating to aim.

**To Reproduce**
1. Start scene
2. Aim curser at the target far from (And in front of)  the ship
3. Your bullets will be inaccurate

**Expected behavior**
The reticle should match the expected trajectory of your attacks.

**Screenshots**
Difficult to take screenshots as the reticle seems to disappear when I use print screen and snipping tool.

**Comment by TeaRussell** [comment]
See also #74
