### ISSUE TITLE
[MODULE] Vampire Projectiles - Life

### ISSUE THREAD

**Issue by MistaMishMash** [Liam-Harrison/Celeritas#114]
### Boss Module - Vampire Projectiles

Basic Functionality:
When a projectile of this kind damages an enemy ship (not an asteroid or some other not-enemy target), the player will restore health proportional to the amount of damage done.

Stats: Projectile damage is decreased to 80% of its original value

Level 1: player recovers 10% of inflicted damage as health.
Subsequent Levels: + 5% of inflicted damage. + 5% damage.

Note: values are guidelines only, please feel free to modify them to see what looks good, feels powerful (it is a boss module) but not game-breaking.
Note: values are quite low as presently there are no drops or other easy ways for the player to recover health, so health steal is very powerful. If this changes, vampire projectiles should recover more health. (Alternatively, if 10% is too much, please lower)

**Comment by 100575155** [comment]
Task Estimation (time): 3
Task Estimation (difficulty): easy

Risks: Unfamiliar with targeting multiple entities in one module (projectile and ship).
Risk Resolution: Will ask for help if stuck

**Comment by 100575155** [comment]
Actual time taken: 2.5 hr
Actual difficulty: Very easy

Testing procedure: Playtest
Test Pass Condition(s): Ship health is healed when projectile hits enemy ship. I will check this by using the health bar and the Debug Log.

Risks: Ship entity is given to Projectile entity to apply heal.
Risk Resolution: Set value of Ship entity within Projectile entity to null so only comes into play when a module specifically targets it. Left a comment describing what it's for.
