### ISSUE TITLE
[BUG] Ship Jitter

### ISSUE THREAD

**Issue by MistaMishMash** [Liam-Harrison/Celeritas#138]
**Describe the bug**
Player ship appears to jitter randomly (ie, sway left and right really quickly) ever since the game speed was increased. May be caused by the aiming system being designed for a slower game.

**To Reproduce**
Play the game, fly around a bit. Sometimes staying still will trigger it. Ship orientation is not smooth.

**Expected behavior**
Ship orientation should be smooth and consistently pointing at or moving towards the player cursor, without jitter

**Additional context**
Liam H mentioned this may be caused by the aiming system being physics based.

**Comment by Liam-Harrison** [comment]
This was resolved some time ago but the issue wasn't closed correctly.
