### ISSUE TITLE
[WEAPON] Shrapnel Cannon implementation

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#159]
A Shrapnel cannon should be implemented so that, upon selection and use within the time of play, it fires and operates properly.

--The shrapnel cannon is a close-range weapon that deals high damage in a close area due to the wide coverage of projectiles. An initial large projectile is launched that, upon travelling a short distance, breaks into smaller low damage projectiles.--

The shrapnel cannon:
1. Should fire at first a single entity that, after a small distance is covered, explode into smaller projectiles.
2. Will have each small projectile do a small amount of damage each.

Additional features:
-The speed of the projectiles (initial and after breaking apart) should not be overly fast.
-The projectiles must slow down (after breaking apart), having each individual projectile despawn once speed reaches 0.
-The damage of these projectiles should be set to 5. Will be balanced over time.

The following polishes can be done later, and will have their own seperate task if not done here.
-The projectiles should be a deep red colour.
-The projectiles should have a lumpy polygonal appearance.

**Additional context**
Refer to mood board on capstone google drive for reference on appearance.

**Comment by MistaMishMash** [comment]
Working on this in sarah/shrapnel cannon. Video of how it's looking right now below, sending to team for feedback.
Am just using asteroids for the projectile graphics for the time being, more will need to be done to make it look prettier later probably.

https://user-images.githubusercontent.com/19755210/128137252-1555cd12-0450-4cab-a1ea-0b44ef411e3c.mp4

**Comment by MistaMishMash** [comment]
Liam H added some changes to the branch so the weapon works correctly with ship modules. Here's an example of it working with the 'chase' modifier (chases the mouse)

https://user-images.githubusercontent.com/19755210/128314570-f8f4fd6d-bf8f-49b2-bc6b-de5a36037235.mp4

And here's one just showing the stock weapon with the updated logic:

https://user-images.githubusercontent.com/19755210/128314654-ea81d3f5-6e94-4ed3-8923-af6c10f9edc3.mp4
