### ISSUE TITLE
[WEAPON] Mining laser

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#161]
A Mining Laser should be implemented so that, upon selection and use within the time of play, it fires and operates properly.

--The mining laser is a long range beam of energy. This beam deals consistent damage over a moderate range.--

The mining laser:
1. Should produce a slightly conical - but straight-pointing - beam of light.

Additional features:
-The laser will produce low damage; however, due to its' constant hit rate, will deal damage consistently and at high quantities.
-The laser should be slightly conical; the beam will taper to a point as it reaches its' maximum range.
-Much like any other weapon, when used with the homing projectile module, this beam can contort into curved lines.
-Will assess starting damage later on, apologies, will add soon

The following polishes can be done later, and will have their own seperate task if not done here.
-The laser should be a very very light blue, representing electricity.
-It should have small sparks running through it.

**Additional context**
Refer to mood board on capstone google drive for reference on appearance.

**Comment by MistaMishMash** [comment]
Currently trying to approach this by using many very fast bullets. Video one just uses very fast bullets with trails:

https://user-images.githubusercontent.com/19755210/128593533-cef51c5f-8318-4041-9af1-787c1bfb76ae.mp4

Video 2 uses more dense bullets, with logic that has them stay closer to one-another, in an attempt to make it look more like a beam

https://user-images.githubusercontent.com/19755210/128593555-3b106874-3a2a-4288-9100-5595fbadcc38.mp4

Have sent these on discord for feedback.

**Comment by MistaMishMash** [comment]
https://user-images.githubusercontent.com/19755210/128633552-c9ac501e-2c6c-4273-91ee-e89c3a74f47c.mp4

^ what it is like now! After Sunday meeting, group is OK with implementing this weapon the way it is. I'm calling it a 'rapid-fire mining laser', though a line/damage over time laser like the one discussed in this issue could definitely be implemented in future.
