### ISSUE TITLE
[DOCUMENTATION] Update Wiki documentation

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#167]
The wiki must be updated to show a more accurate representation of our project given the updated scope. Things must be polished, adjusted, or removed to show clarity and a better idea of our hopeful end product.

**Comment by LiamCMoore** [comment]
Minor changes have been made to most design documentation pages on the wiki.

More significant changes have been made to the UI design page and an entirely new schedule and enemy AI page have been added.

**Comment by LiamCMoore** [comment]
Closing this issue as the current work done is a sufficient minimum. Wiki documentation is an ongoing issue but is the reseponsibility of the entire team.
