### ISSUE TITLE
[DOCUMENTATION] Create semester 2 roadmap

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#168]
A roadmap showing the hopeful milestones and sprints and when they will occur must be done to give structure to semester 2 and keep us all to a specific timeframe.

**Comment by LiamCMoore** [comment]
The roadmap document may be found here: https://docs.google.com/document/d/1CtCLn9-wIxLlVCPzwvzBTf2yHyYb3vTXD8KfzLblisM/edit?usp=sharing

Additional context is provided in the following discord message: https://discord.com/channels/818314997389328464/818335235010986025/872497604464877668

This will be a living document going forward and will be given its own wiki page, once this is done, the issue will be closed.

**Comment by LiamCMoore** [comment]
Relevent Wiki page:

https://github.com/Liam-Harrison/Celeritas/wiki/Semester-2-Development-Schedule

Further edits will be made here, closing issue.
