### ISSUE TITLE
[REQUEST] Player/enemy projectile differentiation

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#191]
The projectiles fired from the player's ship and enemy ships should have a difference in colour to be easily identifiable during playtime.

An example could be having the enemy projectiles be less saturated or darker (the autocannon on the player's side could be a bright lemon yellow, and the enemy's autocannon could be a dulled darker yellow).

Regardless, the main objective is for the projectiles to be differentiated from each other, but not too different so that the player cannot tell:
-what kind of weapons the enemy ships are equipped with
-what effects those enemy weapons have

**Comment by LiamCMoore** [comment]
Spent a lot of my time on this issue this week, turns out a programming implementation is impractical and I just wasted a whole bunch of my time. We're going to need to circle back to this and fix with either an art solution or a some in-unity trickery.

**Comment by LiamCMoore** [comment]
Assigning Lachlan to this issue as he believes he can manage an art-based solution.
