### ISSUE TITLE
[REQUEST] Basic boss fight

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#208]
Using the data of the basic boss fight that was implemented, create a basic boss fight.

To copy from the last task: All basic information for the boss fight should be implemented, as well as assigning the largest ship type to it; the Dromius class Super-Dreadnought's model will be used for this boss fight. Information that should be included involves base health, shields, speed, mass, as well as any other information that can be found on the wiki.

**Comment by TeaRussell** [comment]
Finished in #204
