### ISSUE TITLE
[REQUEST] Ship models

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#216]
Models of all ships must be finished. All ships can be found on the github page "Hulls", with info on how they look available too.

**Comment by TeaRussell** [comment]
Task Estimation (time): 3h (? )

Risk: Art doesn't import to unity well
Risk Resolution: Poke Aiden about it, he has the pipeline in place.

Risk: Takes more time than expected.
Risk Resolution: Will keep everyone updated on progress.  This task is more important than the other assigned to me this week, so it will be my priority.  If it takes more than twice the time I've estimated I will ask for backup!

Risk: People don't like it.
Risk Resolution: That's just art.  Will definitely take feedback and act on it even if I think it makes it look worse, though - this is a group project! Everything needs to fit the style as well as is possible! But if general consensus is it's fine then well, sometimes people just don't like your art and that's okay!
