### ISSUE TITLE
[REQUEST] Ship stats on selection screen

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#239]
The ship selection screen has no information on the ships and their stats. The descriptions do little to allow understanding of the difference between the ships.

The ships should have stats underneath, stating their module slots, amount of weapons, speed, mass, turning speed, base health and base shields.

The stats should be very easily legible, and POP on the screen. Across every ship, they should be in the same place underneath the description so when you switch between ships, it's easy to see the difference in values.

The speed and turning speed (and perhaps mass) could be bars, showing their relevance to minimum vs maximum values. For example, a ship that has a 400 turning speed means nothing to the player, but a bar that is a quarter full shows that this ship has relatively low turning speed to the maximum possible value.

For extra details, please refer to the page "Ship stat visuals" on github (WILL BE CREATED SOON).

**Comment by MistaMishMash** [comment]
Task Estimation (time): 5 hours ?
Does this issue address a risk? Yes, Ebony's playtesting revealed that players can't tell if there are any differences between ships on the selection screen, they assume that all differences are aesthetic. This task will resolve that by providing a little stat summary for each selected ship.

Risks: I'm not too familiar with this part of the project or UI creation in Unity.
Risk Resolution: I completed #240 first, which helped me before more familiar with the menu interface before beginning this task.

Risk: The Wiki stat visuals as described above has not been created yet, so my solution may not be what is envisioned.
Risk resolution: have discussed implementation with Ebony (creative director). Will implement a basic number/stat bar visual at first, and we will work from there.

**Comment by MistaMishMash** [comment]
https://user-images.githubusercontent.com/19755210/131805516-be91f169-534b-46cd-926c-b15ec874e74b.mp4

Progress about 4 and a half hours in, have shown to team for feedback. All functionality is in and working correctly, however c:

**Comment by MistaMishMash** [comment]
Team feedback:
Health/Shield values are very large. Consider dividing them by 100, making them a decimal, to make them more reasonable. (Liam M)
Consider adding dividers to the bars to make them easier to compare visually. (Lachlan)
Need to be able to view ship's module capacity (Ebony)
Instead of putting weapon count, consider putting icons? Eg, 3 bullets = 3 weapons (Ebony)

Currently planning on implementing the mechanical changes first (being able to view module capacity), then will focus on visual changes if capacity and priority permits. (Other tasks may be a higher priority than visual improvements)

**Comment by MistaMishMash** [comment]
Little extra estimation, as I hadn't understood the scope of this task properly:
Estimation for adding hull layout preview to the loadout screen: 3 hours

**Comment by MistaMishMash** [comment]
https://user-images.githubusercontent.com/19755210/132651827-81273830-bbeb-40eb-9587-b4cc7569dac0.mp4

^ hull preview implementation. Took 3 hours 20 minutes to implement.

After sharing with the team for feedback, need to add icons for weapon slots and a number for the number of module slots (squares in the hull)
Estimation for these extra tasks: 2 hours
