### ISSUE TITLE
[REQUEST] Remove weapons from selection screen

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#240]
On the weapons section of the ship selection screen, having weapons equipped allowed little need for the players to notice and look at the weapons.

**Describe the solution you'd like**
The weapons should be removed from the ship, forcing the player to add them themselves. The continue button should be greyed out until the player assigns weapons to every slot. Furthermore, there should be an indicator that the player must select their weapons.

**Describe alternatives you've considered**
The indicator could be a flashing message like "NO WEAPONS SELECTED" or when you click on the greyed out button, a message pops up saying "NO WEAPONS SELECTED", and the weapon section down the bottom flashes lightly red.

**Comment by MistaMishMash** [comment]
Task Estimation (time): I'd expect this task to take 3 hours, so I will estimate it to take 6 hours (as my last prediction was 50% of the actual time required)
Does this issue address a risk? Yes, Ebony's playtesting revealed that many players skip through the ship selection screen without realising that they can choose a variety of weapons to choose from. By having no weapons selected from the onset, players will be forced to choose their own weapons, thus making the weapon selection option clear to them.

Risks: I am very unfamiliar with this part of the game, as I have never worked on the ship selection screen before ! 
Risk Resolution: I will spend some time looking over the ship selection/run start scene to see if I can work out how to implement this. If it is unclear to me after that, I will ask the team for their opinion on how to approach.

**Comment by MistaMishMash** [comment]
https://user-images.githubusercontent.com/19755210/131669469-c0f2fe6d-cb01-456a-8713-9d5957e45871.mp4

progress so far c: after 4 ish hours

**Comment by MistaMishMash** [comment]
Actual time taken: 4 hours

Testing procedure: (pick one) Playtest
Test Pass Condition(s):  Try to begin play with 1 or more 'empty' weapons, confirm that the correct 'you need to equip weapons' message appears and that play cannot begin.
Then try to begin play with valid weapons, normal play should be possible. Both tests were manually confirmed, as shown in the video above.

Risks: Originally, the 'empty' weapon was called 'placeholder' weapon, which was a risk, as players may have thought it was a placeholder until another actual weapon was implemented.
Risk Resolution: Renamed the weapon the be 'empty weapon slot' to make its purpose clearer for future devs.

Risk: players may find the extra step of needing to choose a weapon frustrating?
Risk resolution: observe this in playtesting. Logic is easy to revert if required. (simply equip player ship prefabs with the autocannon again)
