### ISSUE TITLE
[REQUEST] Screen shake when shields broken

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#247]
When the shields reach zero, they will break, causing the player to start taking health damage.

**Describe the solution you'd like**
When these shields break, there should be mild screen shake. There will be a sound effect to accompany this breakage.

**Comment by TeaRussell** [comment]
Task Estimation (time): 0.5-2 depending
Does this issue address a risk? Ehhh

Risk: Haven't played with Cinemachine before
Risk Resolution: Will flail in chat if needed

Risk: Don't know anything bout the sound backend
Risk Resolution: Have asked LiamH in dev chat if there's docs, if not I'll start pestering him directly if it's not all self-evident when I poke it.  Which it almost definitely won't be, but sometimes I'm surprised...

**Comment by TeaRussell** [comment]
Actual time taken: ~2.5h

Testing procedure: (pick one) Playtest
Test Pass Condition(s):  Screen shakes when shield breaks

Risk: SFX implementation may not work
Risk Resolution: I did follow one of Liam H's examples closely, but I don't have the SFX to add to test it!

Risk: Testing takes f o r e v e r
Risk Resolution: Added a 'last wave' button, so there's a super strong ship that spawns so you die quicker.  (I think I need to make it stronger though hahaha.)
