### ISSUE TITLE
[REQUEST] Low Health red vignette

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#248]
When the player is on low health (>15%), a red vignette should appear around the edges of the screen, slowly getting higher in intensity as health depletes. This vignette can flash slightly, mimicing emergency lights on the ship. When health reaches above 15%, the vignette should not be visible.

The vignette will be accompanied with alarm sounds and blaring.

**Describe alternatives you've considered**
There could also be a small text box that appears, stating that you're low on health and might crash any second. For further information or uncertainties, contact Ebony.

**Comment by TeaRussell** [comment]
Task Estimation (time): 3 (complete guess)
Does this issue address a risk? Not directly

Risk: Have not done something like this in Unity before (the vignette thing, I've done event triggers before!)
Risk Resolution: If it takes more than a websearch and some swearing I'll ask for help!

**Comment by TeaRussell** [comment]
Actual time taken: ~3h.  Huh.  It felt like a lot longer than that! Also right on, I managed to guess correctly!

Testing procedure: (pick one) Playtest
Test Pass Condition(s):  SO MUCH PLAYTEST, as it's an in-combat cosmetic change.  Basically, does it work As Expected, or no? If yes, pass! Yay!

Risks: It may Mysteriously Break, as my screen shake code seems to have.  :/
Risk Resolution: I will yell about it until we figure out why.  (The why may just be Unity being a butt, at which point all you can do is fix it, siiiiigh.)
