### ISSUE TITLE
[REQUEST] Explosion upon death

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#249]
When the player reaches 0 health, their ship will explode and a game over screen will be shown.

**Describe the solution you'd like**
Upon the health reaching zero, the camera zooms in on the players ship as final alarms blare. An explosion consumes the player's ship. The enemies stop shooting. On the place where the player's ship once was, after the explosion has dissipated, the text "Game Over" should appear as a fade in. Once that appears, the options "Main Menu" and "Exit" are shown as buttons, allowing the player to go back to the main menu or quit the game respectively.

**Additional context**
The explosion should be large and dramatic. Ideally, it would almost appear in slow motion, being drawn out over 3-4 seconds with lots of sparks, fire, everything just shooting out from this. It will be the focus on the screen, consuming not only the entire player ship, but the majority of the screen as it zooms in. As mentioned in the discord, see FTL, Battlefleet Gothic 2.

**Comment by TeaRussell** [comment]
Task Estimation (time): 6h (guess)
Does this issue address a risk? Not exactly but it'll be a shitty game if we don't have something like this in it.

Risk: While I have used Unity's particle sim system before, it was only in a very basic way, so it might take me a while to get a good-looking explosion.
Risk Resolution: If Unity's system is too difficult, I might be able to use Blender.  I'll also ask people if they have any exp doing related things.

Risk: Timing of camera zoom/explosion/UI stuff might get dodgy, the concept is simple but the execution might get tricky.
Risk Resolution: As ever, if I get stuck/confused/etc, I'll ask for help.

**Comment by TeaRussell** [comment]
Actual time taken: 34:08:36 \*crying*

Testing procedure: (pick one) Playtest
When ship dies, goes boom.  Yes. Player ship and enemy ships!

Risks: MAYBE IT WILL BREAK
Risk Resolution: I will cry at someone until they fix it, probably.  I have spent so fucking long on this whyyyyyy please just work, explosions...
