### ISSUE TITLE
[REQUEST] UI rework

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#251]
From the previous playtests, rework the UI in accordance with player feedback.

The relevant feedback is available on the google drive, under playtesting. For extra information and all feedback, contact Ebony.

**Comment by LiamCMoore** [comment]
Two proposed UI reworks were posted and feedback provided.

It was decided to go with the centre-based UI.

A solution will need to be found for the issue of it block the bottom portion of the screen, limiting the already shortest camera distance.

**Comment by LiamCMoore** [comment]
![image](https://user-images.githubusercontent.com/42259108/131955364-b333be13-b50d-4496-9296-ff9e12f27f9e.png)

This is the template for the new UI.

Closing.
