### ISSUE TITLE
[REQUEST] Delayed shield regeneration by default

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#275]
The shields are quickly depleted, and players find it frustrating when their shields are not regenerated. This causes frustration and annoyance, and due to the malfunction of the shield boost module, there is currently no way to restore your shields once they are damaged.

Shield regeneration will now occur after a period of taking no damage for 6 seconds, to which shield regen will occur at a rate of (for now) 50 per second.

**Comment by 100575155** [comment]
Task Estimation (time): 3hrs

Risks: Values might be off / not feel quite right.
Risk Resolution: Will playtest to find something that fits.

**Comment by 100575155** [comment]
Actual time taken: 2

Testing procedure: Playtest
Test Pass Condition(s): The ship's shields will increase after a set amount of time after damage has been taken. I will check this by using the Debug Log.

Risks: depending on the ship the amount regenerated might not feel right.
Risk Resolution: Will bring up with team discussion, each ship will likely need to be playtested to find a balance.
