### ISSUE TITLE
[MODULE] Overdrive Module - Active

### ISSUE THREAD

**Issue by LiamCMoore** [Liam-Harrison/Celeritas#299]
Active Module - Overdrive Module
Basic Functionality:
Overcharges the ships reactor, diverting an enormous amount of power to the weapons. Massively increases the ships attack speed for a brief period of time.

Stats:
Cooldown: 30 Seconds
Duration: 4 Seconds
Attack Speed Amp: 150% (2.5X the default attack rate)

Level 1: As above.
Subsequent Levels: Duration increased by 1 second per level, attack speed amp increased by 25% per level (150% -> 175% -> 200% etc)

**Comment by MistaMishMash** [comment]
This week (week 8) I have been reassigned from this to #315 due to overlap with Anthony's weekly tasks

**Comment by 100575155** [comment]
Task Estimation (time): 3hr+1hr

Risks: unfamiliar with rate of fire system.
Risk Resolution: Will look into rate of fire module and message team if I get stuck.

Risks: Module doesn't have a icon yet.
Risk Resolution: Added additional time in estimation to create one.

**Comment by 100575155** [comment]
Actual time taken: 4.5hr

Testing procedure: Playtest
Test Pass Condition(s):  When activated, fire rate of ship's weapons increase.

Risks: Sound will bug out due to too many sound effects.
Risk Resolution: Will need to come up with a solution to limit sound effects.
