### ISSUE TITLE
[MODULE] Redundant Shield Cores - Active

### ISSUE THREAD

**Issue by LiamCMoore** [Liam-Harrison/Celeritas#300]
Active Module - Redundant Shield Cores
Basic Functionality:
Energy that would normal be directed to recharging main shielding is instead made to trickle-charge a back-up shielding array. Disables inherent shield recharge but grants an active ability to fully restore all shields.

Stats:
Cooldown: 45 Seconds
Duration: Instant
Fully restores shields
Disables the automatic out-of-combat shield recovery.

Level 1: As above.
Subsequent Levels: Cooldown reduced by 10%, multiplicatively (100% - 90% - 81% - 72.1% - etc) We can't use flat CDR here because we don't want the player getting a 0 second cooldown shield restore.

**Comment by 100575155** [comment]
Task Estimation (time): 4 + 1

Risks: Might take some time to whip up a suitable effect and icon
Risk Resolution: Added additional hour to estimation. Will tell team, ask for help if stuck.
