### ISSUE TITLE
[MODULE] RADIANT Immortality Protocol - Active

### ISSUE THREAD

**Issue by LiamCMoore** [Liam-Harrison/Celeritas#301]
Active Module - RADIANT Immortality Protocol 
Basic Functionality:
Projects an advanced hard-light shell around the ship, granting temporary immunity to damage.

Stats:
Cooldown: 30 Seconds
Duration: 1.5 Seconds
Grants total immunity to damage.

Level 1: As above.
Subsequent Levels: Duration increased by 0.5 Seconds.

**Comment by 100575155** [comment]
Task Estimation (time): 4 + 1

Risks: Might take some time to whip up a suitable effect and icon
Risk Resolution: Added additional hour to estimation. Will tell team, ask for help if stuck.

**Comment by 100575155** [comment]
Actual time taken: 4hr

Testing procedure: Playtest
Test Pass Condition(s):  When activated, ship will not take damage for set period of time.

Risks: Effect is pretty sudden, don't know if people will like it.
Risk Resolution: Will get feedback from team / playtests.
