### ISSUE TITLE
[MODULE] SHIVA Destruction Core - Active

### ISSUE THREAD

**Issue by LiamCMoore** [Liam-Harrison/Celeritas#302]
Active Module - SHIVA Destruction Core
Basic Functionality:
Converts a large amount of Scrap Metal into unstable quantum mass, before briefly phasing you out of reality to protect you from the apocalyptic explosion that follows.

Stats:
Cooldown: 30 Seconds
Duration: 0.5 Seconds
AoE: The entire screen, we'll tweek this to make it work.
Damage: 750
Grants Immunity to damage for the duration
Costs 50 Scrap Metal to activate.

Level 1: As above.
Subsequent Levels: Damage increased by 250 per level.

**Comment by 100575155** [comment]
Task Estimation (time): 4 + 2

Risks: Might take some time to whip up a suitable effect
Risk Resolution: Added additional 2 hours to estimation. Will tell team, ask for help if stuck.
