### ISSUE TITLE
[BUG] Invisible ships

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#312]
**Describe the bug**
Some ships in game appear invisible, only their projectiles and engines showing up in the game arena.

**To Reproduce**
1. Start the game.
2. Select a ship, enter weapons, etc - just do all necessary actions to get into the game.
3. Go to events, completing them by killing all enemies.
4. Repeat above step maybe 4-5 times, or until you encounter an enemy ship that is invisible.
5. locate this ship by following all projectiles to origin, until encountering an enemy ship that is invisible.

**Expected behavior**
All ships should be visible.

Only seems to happen with later enemies that are spawned, never the earlier ones.

**Comment by 100575155** [comment]
Fixed in pull request #298
