### ISSUE TITLE
[REQUEST] Gain new module at 100 Rare Metals

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#356]
Once the player collects 100 rare metals, a module should be given to the player. They will be able to select it in the select 1-of-3 module screen. The fact that 100 rare metals translates to getting a new module should be conveyed, for example; the rare metal counter appears along with a notice of "you can now craft a module!" and the rare metal counter resetting to zero. Something similar can also be done.

**Comment by TeaRussell** [comment]
Task Estimation (time): 2-4
Does this issue address a risk? No this is more a game balance thing I think

Risks: I haven't touched any of these systems before!! 8D
Risk Resolution: Will flail in chat as normal.
