### ISSUE TITLE
[BUG] Acid module doesn't increase damage on level up

### ISSUE THREAD

**Issue by ebsmarch** [Liam-Harrison/Celeritas#379]

**Comment by 100575155** [comment]
Task Estimation (time): 2hr

Risks: Haven't touched this module before, might take longer to find the issue.
Risk Resolution: Will ask for assistance if I get stuck.

**Comment by 100575155** [comment]
Actual time taken: 1hr

Testing procedure: Playtest
Test Pass Condition(s): Projectiles will apply damage over time which will increase in damage and duration as the module levels up.

Risks: None, bug was in the module prefab, the logic still works fine.
Risk Resolution: Fixed prefab.
