### ISSUE TITLE
[REQUEST] Move module selection interface off the build interface

### ISSUE THREAD

**Issue by FathomlessFunction** [Liam-Harrison/Celeritas#387]
**Is your feature request related to a problem? Please describe.**
Currently, if you get several modules, you have to select all of them before you can build things.

**Describe the solution you'd like**
Move the module selection interface up off the build interface, so that you can build freely while pending module selections exist.
Note that because of this updated positioning, players might not notice the module selection window, so it may need to become a bit more shiny / prominent, so they don't miss it.

**Comment by MistaMishMash** [comment]
Video showing the updated interface, and how you can now build on your ship while module selection is pending.

https://user-images.githubusercontent.com/19755210/137856384-23a3575e-0957-43c2-9586-5708a396758c.mp4
