### ISSUE TITLE
[BUG] Tooltip title sizing

### ISSUE THREAD

**Issue by TeaRussell** [Liam-Harrison/Celeritas#401]
**Describe the bug**
From the buglist:
- some module titles appear to overlap the module preview icon. (might need to shorten their names)

**To Reproduce**
Mouse over a module with a long name

**Expected behavior**
Entire name should be readable!

**Screenshots**
![image](https://user-images.githubusercontent.com/19548288/139070869-dfd2ba54-8b80-4e64-8644-e292195f80a9.png)

**Comment by Liam-Harrison** [comment]
Closed in #409
