### ISSUE TITLE
[MODULE] Ship Speed

### ISSUE THREAD

**Issue by LiamCMoore** [Liam-Harrison/Celeritas#41]
### Basic Module
Basic functionality: Increases the speed and acceleration rate of the players ship by a small flat amount and a large percentage amount. (50/50%, these numbers are relative to those used on the 'hull module' wiki page.)

Upgrade Functionality: Each level increases the effect of the module by 50/50%.

**Comment by MistaMishMash** [comment]
Addressed in #146
