### ISSUE TITLE
[MODULE] Weapon Projectile Count (Volley)

### ISSUE THREAD

**Issue by LiamCMoore** [Liam-Harrison/Celeritas#42]
### Basic Module
Basic functionality: Increases the number of projectiles fired from the players weapon, these additional projectiles are spread in a straight line away from the player ship. Initially, the module provides 2 additional projectiles. 

Upgrade Functionality: Each level of the module increases the number of projectiles fired by 2. (3 -> 5 -> 7 etc).

**Comment by MistaMishMash** [comment]
Addressed in #146
