### ISSUE TITLE
[MODULE] Energy Convalescence Drive

### ISSUE THREAD

**Issue by LiamCMoore** [Liam-Harrison/Celeritas#60]
### Custom Module
Basic functionality: Energy Convalescence Drive. Increased projectile damage per meter travelled 

Upgrade Functionality: 
- 5% damage increase per meter to a max of 6m, with a 2% increase per level (level 1 damage increases by 5%, level 2 damage increases by 7%, level 3 damage increases by 9% etc)

**Comment by 100575155** [comment]
Task Estimation (time): 4
Task Estimation (difficulty): easy

Risks: Unfamiliar with projectile entity system.
Risk Resolution: Will reach out to team if stuck.
